import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

import { cn } from "@/lib/utils";

import "./globals.css";

const vazirmatn = Vazirmatn({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-vazirmatn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={cn(vazirmatn.variable, "font-vazirmatn")}>
        {children}
      </body>
    </html>
  );
}
